"""Add vehicle_type field to Incident model

Revision ID: 22beaede0afd
Revises: dfc056209ab4
Create Date: 2025-03-07 00:26:28.677519

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '22beaede0afd'
down_revision = 'dfc056209ab4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('incident', schema=None) as batch_op:
        batch_op.add_column(sa.Column('vehicle_type', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('incident', schema=None) as batch_op:
        batch_op.drop_column('vehicle_type')

    # ### end Alembic commands ###
